vich_uploader:
    db_driver: orm

    mappings:
       products:
            uri_prefix: /images/miniatures
            upload_destination: '%kernel.project_dir%/public/images/miniatures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
